FROM almalinux:8
#RUN cd /tmp/
#docker ignores previous cd command, every instruction it assumes it is in home directory. home directory "\"
WORKDIR /tmp
#for all the coming instructions /tmp will be the directory.
RUN echo "hello world!!" > hello.txt
RUN echo "Hey hai!!" > hi.txt
