FROM almalinux:8
#ADD and COPY instruction are same, they can copy the files from local to the image but the ADD instruction has some capabilities it can directly download the content from internet
#ADD instruction can untar the tar files
ADD https://raw.githubusercontent.com/techworldwithsiva/docker-install-commands/master/docker-install.sh /tmp/docker.sh
ADD sample-1.tar /tmp/